adding SQLite to save data on a server to server basis (resolves #12)
TrojanerHD/AdventofCode-Bot pull request #19
Opened 2020-12-06 18:33 UTC by LeMoonStar

Using SQLite is one way to save the configuration on a (discord) server to (discord) server basis, and better suited than a JSON file for this use case. This Branch will be used to implement a helper class/function to save data for each (discord) server and therefore the configuration of each (discord) server containing the AoC Session and the AoC leaderboard ID.

2020-12-06 18:46 UTC, TrojanerHD requested changes

2020-12-06 18:46 UTC, TrojanerHD commented on package.json
> +    "@types/sqlite3": "^3.1.6",
Type packages belong in dev dependencies:
```sh
yarn remove @types/sqlite3
yarn add -D @types/sqlite3
```
or
```
npm remove @types/sqlite3
npm install @types/sqlite3 --save-dev

2020-12-06 18:52 UTC, TrojanerHD submitted a review, later dismissed

2020-12-08 18:26 UTC, daanbreur commented
Meaby best to have the enable type of `boolean` instead of INTEGER

2020-12-08 18:36 UTC, LeMoonStar commented
> Meaby best to have the enable type of `boolean` instead of INTEGER

SQLite only supports
+ NULL
+ INTEGER
+ REAL
+ TEXT
+ BLOB

the INTEGER type scales depending on the input, it can be 1 byte, 2, 3, 4, 6 and 8 byte, since working with less than 1 byte is uncommon (booleans are one byte too, even in languages like c), so it will also use the same space.

(source for the types: https://www.sqlite.org/datatype3.html )

2020-12-08 18:38 UTC, LeMoonStar commented
> > Meaby best to have the enable type of `boolean` instead of INTEGER
> 
> SQLite only supports
> 
>     * NULL
> 
>     * INTEGER
> 
>     * REAL
> 
>     * TEXT
> 
>     * BLOB
> 
> 
> the INTEGER type scales depending on the input, it can be 1 byte, 2, 3, 4, 6 and 8 byte, since working with less than 1 byte is uncommon (booleans are one byte too, even in languages like c), so it will also use the same space.
> 
> (source for the types: https://www.sqlite.org/datatype3.html )

also, using the boolean on the JS/TS side would lead to issues when interacting with the database, cause JS converts it to the `true` and `false` string representation, which would be stored as a string by SQLite too, which would then, in the end, use more space

2020-12-08 21:06 UTC, joblo2213 commented
Just my take on this, you might ignore it cause it really doesn't matter for a small project like this one. 

Normally in such a project you would take a more general approach that works well with any sql database, not just sqlite. 
So if the project grows and you might want something better suited for larger scale you can easily migrate for example to MySql.

This also means using the more common datatypes among traditional sql implementations, like for example BOOLEAN, VARCHAR(255), .... 

SQLite works well with them too and will automatically convert, see point 3.1.1 in the link you just posted.

2020-12-08 21:20 UTC, LeMoonStar commented
> Just my take on this, you might ignore it cause it really doesn't matter for a small project like this one. 
> 
> Normally in such a project you would take a more general approach that works well with any sql database, not just sqlite. 
> So if the project grows and you might want something better suited for larger scale you can easily migrate for example to MySql.
> 
> This also means using the more common datatypes among traditional sql implementations, like for example BOOLEAN, VARCHAR(255), .... 
> 
> SQLite works well with them too and will automatically convert, see point 3.1.1 in the link you just posted.

that's true, and I probably should migrate to use these data types, I also already worked with mariaDB (basically mysql) on a commercial project and therefore have a bit of experience with it, so it shouldn't be a problem.

I also only chose SQLite cause it is less work and has everything we need for this project and doesn't need an external application, while the other option was a JSON file, which isn't really meant for this use (see issue #12)

the goal for now was only to get it working, which as you can see still doesn't work, only reading does. the SQL is by far not finished yet and is definitely subject to change in the future

2020-12-08 21:31 UTC, TrojanerHD requested changes
I forgot to add to the [CONRTRIBUTING.md](https://github.com/TrojanerHD/AdventofCode-Bot/blob/main/CONTRIBUTING.md) that you should prefix class variables with `_` in order to distinguish between class variables, local variables and class functions.

Other than that small typos and minor changes to the code were suggested

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +    this.db = new Database(file);
```suggestion
    this._db = new Database(file);
```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +   *
```suggestion

```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +   * @param id the Gulid ID to identifie the rows
```suggestion
   * @param id the Guild ID to identify the rows
```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +      this.db.get(sql, params, (err: Error, row: any) => {
```suggestion
      this._db.get(sql, params, (err: Error, row: any) => {
```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +        .then((row) => {
```suggestion
        .then((row: any) => {
```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +   * Creates all reuqired tables if they don't exist.
```suggestion
   * Creates all required tables if they don't exist.
```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +   * @returns a void promise, for error andling only
```suggestion
   * @returns a void promise, for error handling only
```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +   * @param params parameters for placeholders. automatically sanitized.
```suggestion
   * @param params parameters for placeholders. Automatically sanitized
```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +   * @returns a void promise, for error andling only
```suggestion
   * @returns a void promise, for error handling only
```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +      this.db.run(sql, params, (result: RunResult, err: Error) => {
```suggestion
      this._db.run(sql, params, (result: RunResult, err: Error) => {
```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +   * @param params parameters for placeholders. automatically sanitized.
```suggestion
   * @param params parameters for placeholders. Automatically sanitized
```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +   * @returns a promise for a any object, containing the data of the row the query fetched.
```suggestion
   * @returns a promise for an any object containing the data of the row the query fetched
```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +      this.db.all(sql, params, (err: Error, rows: any[]) => {
```suggestion
      this._db.all(sql, params, (err: Error, rows: any[]) => {
```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +   * @param params parameters for placeholders. automatically sanitized.
```suggestion
   * @param params parameters for placeholders. Automatically sanitized
```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +   * @returns a promise for an any array, containing all rows the query fetched.
```suggestion
   * @returns a promise for an any array containing all rows the query fetched
```

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +export default interface ServerInfo {
```suggestion
export interface ServerInfo {
```
The `default` keyword is only used for when you import the file with `import SomeName from 'xy';`. You shouldn't be allowed to have one interface and one class both default exported at the same time. I wonder why TypeScript didn't complain

2020-12-08 21:31 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +        .catch((err) => reject(err));
```suggestion
        .catch((err: Error) => reject(err));
```

2020-12-08 21:39 UTC, LeMoonStar commented on src/DatabaseHelper.ts
> +  public db: Database;
also, in case you are wondering, it os only public for testing purposes. it'll be private later

2020-12-08 23:16 UTC, TrojanerHD requested changes
Removed unused imports

2020-12-08 23:16 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +import { Server } from 'http';
```suggestion

```

2020-12-08 23:16 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +import { Database, RunResult, Statement } from 'sqlite3';
```suggestion
import { Database, RunResult } from 'sqlite3';
```

2020-12-09 16:43 UTC, LeMoonStar commented
If nobody finds a problem or has another idea, this PR is ready to merge.

2020-12-09 17:04 UTC, daanbreur approved these changes

2020-12-09 17:05 UTC, daanbreur submitted a review, later dismissed

2020-12-09 22:02 UTC, TrojanerHD requested changes
+ Turned beginnings of sentences in JSDoc into uppercase
+ Corrected typos
+ Defined generic types for all promises

2020-12-09 22:02 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +    return new Promise((resolve, reject) => {
```suggestion
    return new Promise<any>((resolve, reject) => {
```

2020-12-09 22:02 UTC, TrojanerHD commented on src/DatabaseHelper.ts
> +    return new Promise((resolve, reject) => {
```suggestion
    return new Promise<any[]>((resolve, reject) => {
```

2020-12-09 22:22 UTC, TrojanerHD approved these changes

2020-12-09 22:23 UTC, merged